MANTA-5458 want longer log upload splay time
joyent/manta-scripts pull request #9
Opened 2021-10-25 22:49 UTC by numericillustration

These changes reflect what we have hot patched some of our larger scale environments with to mitigate the thundering herd of log uploads from causing degradation to user traffic

2021-10-25 22:50 UTC, numericillustration commented
An alternative would be to have the script get a config file that config-agent generates from a template sourcing some tunable values set in sapi for splay range

2021-10-26 18:35 UTC, bahamat commented
Copyright for both files needs updating.

2021-10-26 18:53 UTC, bahamat requested changes

2021-10-26 18:53 UTC, bahamat commented on backup.sh
This should probably have a comment similar to the other file.

Both files need copyright update.

2024-04-26 16:22 UTC, numericillustration commented
I'd be happy to make these updates but I lack commit rights to these repos now.  Would the appropriate thing be to make a PR from a personal fork now?

2024-04-26 17:45 UTC, danmcd commented
See #10 for the continuation of this.

2024-04-26 17:45 UTC, closed without merging